version: "3.7"

services:

  torrent:
    container_name: 'rutorrent'
    image: mondedie/rutorrent:latest
    environment:
      TZ: 'Asia/Seoul'
      UID: 1000
      GID: 1000
      HTTP_AUTH: 'true'
      PORT_RTORRENT: 46000
    ports:
      - 8080:8080
      - 46000:46000
    volumes:
      - /home/media/config:/config
      - /home/media/data:/data

  dlna:
    container_name: 'minidlna'
    image: vladgh/minidlna:latest
    restart: always
    environment:
      TZ: 'Asia/Seoul'
      MINIDLNA_MEDIA_DIR: '/media'
      MINIDLNA_FRIENDLY_NAME: 'MiniDLNA'
    ports:
      - 8200:8200
    #  - 1900:1900/udp
    volumes:
      - /home/media/data/complete:/media