version: "3.7"

services:

  file:
    container_name: 'samba'
    image: dperson/samba:latest
    restart: always
    environment:
      TZ: 'Asia/Seoul'
      IMPORT: '/etc/samba/smbpassword'
      WORKGROUP: 'ZZIZILY'
      USERID: 1000
      GROUPID: 1000
    #network:
    #  - overlay
    ports:
      - 139:139
      - 445:445
    volumes:
      - media-data:/mount
      - ./smb.conf:/etc/samba/smb.conf
      - ./smbpassword:/etc/samba/smbpassword

  torrent:
    container_name: 'rtorrent'
    image: mondedie/rutorrent:latest
    restart: always
    environment:
      TZ: 'Asia/Seoul'
      UID: 1000
      GID: 1000
      HTTP_AUTH: 'true'
      PORT_RTORRENT: 46000
    #networks:
    #  - overlay
    ports:
      - 9090:8080
      - 46000:46000
    volumes:
      - media-config:/config
      - media-data:/data

  dlna:
    container_name: 'minidlna'
    image: vladgh/minidlna:latest
    restart: always
    environment:
      TZ: 'Asia/Seoul'
      MINIDLNA_MEDIA_DIR: '/media'
      MINIDLNA_FRIENDLY_NAME: 'MiniDLNA'
    #networks:
    #  - overlay
    ports:
      - 8200:8200
    #  - 1900:1900/udp
    volumes:
      - media-data:/media

volumes:
  media-data:
  media-config:

#networks:
#  overlay:
