version: "3.7"

services:

  torrent:
    container_name: 'rutorrent'
    image: mondedie/rutorrent:latest
    environment:
      TZ: 'Asia/Seoul'
      UID: 1000
      GID: 1000
      HTTP_AUTH: 'true'
      PORT_RTORRENT: 46000
    ports:
      - 8080:8080
      - 46000:46000
    volumes:
      - /home/media/config:/config
      - /home/media/data:/data