version: "3.7"

services:

  file:
    container_name: 'samba'
    image: dperson/samba:latest
    restart: always
    environment:
      TZ: 'Asia/Seoul'
      USER: "crom;qwe123"
      WORKGROUP: 'ZZIZILY'
      USERID: 1000
      GROUPID: 1000
      SHARE: "media;/mount;yes;no;no;crom;'none';'none';'media"
    networks:
      - default
    ports:
      # - "137:137/udp" # required to advertise shares (NMBD)
      # - "138:138/udp" # required to advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
    volumes:
      - media-data:/mount

  torrent:
    container_name: 'rutorrent'
    image: mondedie/rutorrent:latest
    restart: always
    environment:
      TZ: 'Asia/Seoul'
      UID: 1000
      GID: 1000
      HTTP_AUTH: 'true'
      PORT_RTORRENT: 46000
    networks:
      - default
    ports:
      - 8080:8080
      - 46000:46000
    volumes:
      - media-data:/data

  # dlna:
  #   container_name: 'minidlna'
  #   image: vladgh/minidlna:latest
  #   restart: always
  #   environment:
  #     TZ: 'Asia/Seoul'
  #     MINIDLNA_MEDIA_DIR: '/media'
  #     MINIDLNA_FRIENDLY_NAME: 'MiniDLNA'
  #   networks:
  #     - default
  #   ports:
  #     - 8200:8200
  #   #  - 1900:1900/udp
  #   volumes:
  #     - media-data:/media

volumes:
  media-data:
  media-config:

networks:
  default:
